// Prints a small title map of every explainer (free and premium) so the app can list locked lessons
// without shipping their sources. Usage: node tools/xpmeta.js > src/09a-xpmeta.js
const fs = require("fs"), path = require("path"), vm = require("vm");
const out = {}, P = (v, i) => Array.isArray(v) && v.length === 2 && v.every(x => typeof x === "string") ? v[i] : v;
const ctx = { window: {} }; ctx.window.XP = { ready: true, bi: D => { out[D.key] = { sk: D.sk, ord: D.ord || 50, t: [P(D.title, 0), P(D.title, 1)], m: [P(D.min, 0), P(D.min, 1)], g: D.goals && D.goals[0] ? [P(D.goals[0], 0), P(D.goals[0], 1)] : null, n: D.scenes.length, q: (D.quiz || []).length }; } };
ctx.XP = ctx.window.XP; vm.createContext(ctx);
const dir = path.join(__dirname, "..", "xpsrc");
for (const f of fs.readdirSync(dir).filter(f => f.endsWith(".js")).sort()) vm.runInContext(fs.readFileSync(path.join(dir, f), "utf8"), ctx, { filename: f });
process.stdout.write("/* generated by tools/xpmeta.js — explainer titles (do not edit) */\nvar XPT = " + JSON.stringify(out) + ";\n");
