/* English explainers: arith */
(function(){ if(!window.XP||!XP.ready) return;
/* a strip of n equal boxes, left to right; returns items keyed p0..p(n-1) */
function strip(p,{x,y,w,h,n,colors,texts,s=20,cls}){ const o={}, sw=w/n;
  for(let i=0;i<n;i++) o[p+i]={type:'box',x:x+i*sw,y,w:sw,h,rx:4,c:Array.isArray(colors)?colors[i]:(colors||'surface'),text:texts?texts[i]:undefined,s,cls};
  return o; }
const ks=(p,n)=>Array.from({length:n},(_,i)=>p+i);
/* a table row, left to right: fraction · decimal · percent */
function trow(p,y,a,b,c,{hdr=false}={}){ const cls=hdr?'t-pri':'t-ink';
  return { [p+'b']:{type:'box',x:100,y:y-24,w:470,h:36,rx:8,c:hdr?'prisoft':'surface2',stroke:false},
    [p+'a']:{type:'text',x:180,y:y,s:hdr?20:24,text:a,cls}, [p+'d']:{type:'text',x:335,y:y,s:hdr?20:24,text:b,cls}, [p+'p']:{type:'text',x:490,y:y,s:hdr?20:24,text:c,cls} }; }
const rk=p=>[p+'b',p+'a',p+'d',p+'p'];
const CMP=['A: the first is greater','B: the second is greater','C: they are equal','D: cannot be determined'];

/* ================= 1. order of operations ================= */
XP.add({ key:'en-ar-order', lang:'en', sk:'arith', ord:10, title:'Order of operations', min:'3 min',
  goals:['See why everyone needs one fixed order','Apply the four steps: brackets, powers, × and ÷, + and −','Avoid the “multiply first” trap','Work out a mixed expression mentally'],
  scenes:[
  { t:'Why an order?',
    items:{ q:{type:'eq',x:320,y:130,s:54,text:'2 + 3 × 4'},
      wbox:{type:'box',x:60,y:180,w:230,h:62,c:'badsoft',text:'5 × 4 = 20',s:28,ltr:true}, wx:{type:'cross',x:175,y:290},
      rbox:{type:'box',x:350,y:180,w:230,h:62,c:'oksoft',text:'2 + 12 = 14',s:28,ltr:true}, rx:{type:'check',x:465,y:290} },
    beats:[
      { say:'A simple question to start: two plus three times four. What do you get?', show:['q'] },
      { say:'Working straight through gives five times four, which is twenty. That’s wrong.', show:['wbox','wx'] },
      { say:'Multiplying comes first: three times four is twelve, plus two is fourteen.', show:['rbox','rx'] },
      { say:'So we all follow one fixed order, or two people would get two answers.', hl:['rbox'] },
    ]},
  { t:'The four-step ladder',
    items:{ c1:{type:'circle',cx:100,cy:95,r:24,c:'pri',text:'1',s:24,cls:'t-inv'}, b1:{type:'box',x:140,y:72,w:370,h:46,c:'n3',text:'Brackets  ( )',s:24,cls:'t-note'},
      c2:{type:'circle',cx:100,cy:157,r:24,c:'pri',text:'2',s:24,cls:'t-inv'}, b2:{type:'box',x:140,y:134,w:370,h:46,c:'n2',text:'Powers: x², x³',s:24,cls:'t-note'},
      c3:{type:'circle',cx:100,cy:219,r:24,c:'pri',text:'3',s:24,cls:'t-inv'}, b3:{type:'box',x:140,y:196,w:370,h:46,c:'n1',text:'Multiply and divide',s:24,cls:'t-note'},
      c4:{type:'circle',cx:100,cy:281,r:24,c:'pri',text:'4',s:24,cls:'t-inv'}, b4:{type:'box',x:140,y:258,w:370,h:46,c:'n0',text:'Add and subtract',s:24,cls:'t-note'},
      h3:{type:'text',x:572,y:226,s:18,text:'left to right',hand:true}, h4:{type:'text',x:572,y:288,s:18,text:'left to right',hand:true} },
    beats:[
      { say:'Picture a ladder with four steps. Step one: brackets.', show:['c1','b1'] },
      { say:'Step two: powers, like squares and cubes.', show:['c2','b2'] },
      { say:'Step three: multiplying and dividing share one step. Work left to right.', show:['c3','b3','h3'] },
      { say:'Step four: adding and subtracting, again one step, left to right.', show:['c4','b4','h4'] },
    ]},
  { t:'The multiply-first trap',
    items:{ q:{type:'eq',x:320,y:115,s:50,text:'24 ÷ 4 × 2'},
      wbox:{type:'box',x:60,y:160,w:230,h:62,c:'badsoft',text:'24 ÷ 8 = 3',s:34,ltr:true}, wx:{type:'cross',x:175,y:262},
      rbox:{type:'box',x:350,y:160,w:230,h:62,c:'oksoft',text:'6 × 2 = 12',s:34,ltr:true}, rx:{type:'check',x:465,y:262},
      tip:{type:'note',x:320,y:318,w:380,h:52,c:'n0',text:'Same step? Left to right',size:22,rot:-1} },
    beats:[
      { say:'Now a very common trap: twenty-four divided by four times two.', show:['q'] },
      { say:'Many multiply first and get twenty-four divided by eight, which is three.', show:['wbox','wx'] },
      { say:'But they share a step, so go left to right: twenty-four divided by four is six, times two is twelve.', show:['rbox','rx'] },
      { say:'Same with adding and subtracting: ten minus three plus two is nine, not five.', show:['tip'] },
    ]},
  { t:'Your turn: climb the ladder',
    items:{ q:{type:'eq',x:320,y:100,s:46,text:'20 − 3 × (5 − 3)²'},
      s1:{type:'eq',x:320,y:200,s:26,text:'(5 − 3) = 2,  2² = 4',cls:'t-ink2'}, s2:{type:'eq',x:320,y:250,s:28,text:'3 × 4 = 12',cls:'t-ink2'},
      s3:{type:'box',x:220,y:275,w:200,h:52,c:'n0',text:'20 − 12 = 8',s:28,cls:'t-note',ltr:true} },
    beats:[
      { say:'Your turn. Climb the ladder one step at a time.', show:['q'] },
      { say:'Twenty minus three times the square of five minus three. What is the result?', hl:['q'] },
    ],
    ask:{ opts:['68','8','14','4'], a:1,
      right:'Well done! The bracket is two, squared is four, times three is twelve, so the answer is eight.',
      wrong:'Bracket first: two. Squared: four. Three times four is twelve, and twenty minus twelve is eight.',
      show:['s1','s2','s3'] } },
  ],
  quiz:[
    {q:'6 + 18 ÷ 3 × 2 = ?', o:['8','18','7','16'], a:1, e:'Divide first because it comes first: 18 ÷ 3 = 6, then 6 × 2 = 12, then 6 + 12 = 18.'},
    {q:'(4 + 2)² − 4 × 5 = ?', o:['16','10','80','20'], a:0, e:'The bracket is 6 and 6² = 36; then 4 × 5 = 20, so 36 − 20 = 16.'},
    {q:'Compare. First: 12 − 4 + 2.  Second: 12 − (4 + 2).', o:CMP, a:0, e:'First, left to right: 12 − 4 = 8, then 8 + 2 = 10. Second: 12 − 6 = 6. So the first is greater.'},
  ] });

/* ================= 2. fractions ================= */
XP.add({ key:'en-ar-frac', lang:'en', sk:'arith', ord:20, title:'Fractions from zero', min:'4 min',
  goals:['Picture a fraction: numerator and denominator','Build equivalent fractions and simplify them','Add two fractions after matching denominators','Compare two fractions by cross-multiplying'],
  scenes:[
  { t:'What is a fraction?',
    items:{ pie0:{type:'pie',cx:180,cy:200,r:105,parts:4,fill:0}, pie3:{type:'pie',cx:180,cy:200,r:105,parts:4,fill:3,c:'pink'},
      num:{type:'text',x:345,y:165,s:64,text:'3',cls:'t-pri'}, bar:{type:'line',x1:310,y1:185,x2:380,y2:185,cls:'s-ink'}, den:{type:'text',x:345,y:252,s:64,text:'4',cls:'t-pri'},
      ln:{type:'text',x:400,y:150,s:20,text:'numerator: parts taken',hand:true,anchor:'start'}, ld:{type:'text',x:400,y:238,s:20,text:'denominator: equal parts',hand:true,anchor:'start'} },
    beats:[
      { say:'A fraction is part of a whole. Cut this circle into four equal pieces.', show:['pie0'] },
      { say:'Shade three of them, and you have three quarters.', hide:['pie0'], show:['pie3','num','bar','den'] },
      { say:'The bottom number, the denominator, says how many equal pieces make the whole.', show:['ld'], hl:['den'] },
      { say:'The top number, the numerator, says how many pieces you took.', show:['ln'], hl:['num'] },
    ]},
  { t:'Equivalent fractions',
    items:Object.assign({},
      strip('a',{x:120,y:72,w:360,h:44,n:2,colors:['pink','surface2']}),
      strip('b',{x:120,y:142,w:360,h:44,n:4,colors:['pink','pink','surface2','surface2']}),
      strip('c',{x:120,y:212,w:360,h:44,n:8,colors:['pink','pink','pink','pink','surface2','surface2','surface2','surface2']}),
      { la:{type:'eq',x:550,y:103,s:28,text:'1/2'}, lb:{type:'eq',x:550,y:173,s:28,text:'2/4'}, lc:{type:'eq',x:550,y:243,s:28,text:'4/8'},
        rule:{type:'note',x:320,y:312,w:470,h:54,c:'n0',text:'Top and bottom × the same number',size:22,rot:-1} }),
    beats:[
      { say:'Half of this strip is shaded. That’s one half.', show:[...ks('a',2),'la'], gap:.15 },
      { say:'Cut each piece in two: now it’s two quarters, and the shaded area is the same.', show:[...ks('b',4),'lb'], gap:.12 },
      { say:'Again: four eighths. Three fractions, one value: equivalent fractions.', show:[...ks('c',8),'lc'], gap:.08 },
      { say:'The rule: multiply top and bottom by the same number, or divide both to simplify.', show:['rule'] },
    ]},
  { t:'Adding fractions',
    items:Object.assign({},
      { e1:{type:'eq',x:320,y:95,s:34,text:'1/5 + 2/5 = 3/5'} },
      strip('s',{x:170,y:118,w:300,h:40,n:5,colors:['pink','pri','pri','surface2','surface2']}),
      { w1:{type:'eq',x:320,y:215,s:30,text:'1/5 + 2/5 = 3/10',cls:'t-bad'},
        e3:{type:'box',x:95,y:255,w:450,h:58,c:'n3',text:'1/2 + 1/4 = 2/4 + 1/4 = 3/4',s:28,cls:'t-note',ltr:true} }),
    beats:[
      { say:'Same denominators? Add the numerators and keep the denominator.', show:['e1'] },
      { say:'One fifth plus two fifths is three fifths. Same-size pieces, so just count them.', show:ks('s',5), gap:.12 },
      { say:'The trap: never add the denominators. Three tenths is wrong.', show:['w1'], strike:['w1'] },
      { say:'Different denominators? Match them first: a half is two quarters, so the sum is three quarters.', show:['e3'] },
    ]},
  { t:'Which is bigger?',
    items:{ v1:{type:'box',x:95,y:62,w:210,h:56,c:'n1',text:'First:  2/3',s:26,cls:'t-note',ltr:true}, v2:{type:'box',x:335,y:62,w:210,h:56,c:'n3',text:'Second:  3/4',s:26,cls:'t-note',ltr:true},
      r1:{type:'eq',x:200,y:205,s:32,text:'2 × 4 = 8'}, r2:{type:'eq',x:440,y:205,s:32,text:'3 × 3 = 9'}, ck:{type:'check',x:440,y:265},
      gt:{type:'eq',x:320,y:320,s:24,text:'9 > 8, so the second is greater',cls:'t-pri'} },
    beats:[
      { say:'Now compare two thirds with three quarters.', show:['v1','v2'] },
      { say:'The trick: cross-multiply each numerator by the other denominator, then compare.', hl:['v1','v2'] },
      { say:'Try it. Which choice is correct?', hl:['v2'] },
    ],
    ask:{ opts:CMP, a:1, column:true, y:156, s:20,
      right:'Correct! Two times four is eight, three times three is nine, so the second is greater.',
      wrong:'Cross-multiply: two times four is eight, three times three is nine. So three quarters is greater.',
      show:['r1','r2','ck','gt'] } },
  ],
  quiz:[
    {q:'Which fraction is equivalent to 3/4?', o:['6/9','9/12','4/5','6/10'], a:1, e:'Multiply top and bottom by 3: 3/4 = 9/12.'},
    {q:'1/3 + 1/6 = ?', o:['2/9','1/2','1/9','2/3'], a:1, e:'Match denominators: 2/6 + 1/6 = 3/6 = 1/2.'},
    {q:'Which fraction is the largest?', o:['3/5','5/8','2/3','4/7'], a:2, e:'As decimals: 0.6, 0.625, about 0.67 and about 0.57, so 2/3 is largest.'},
  ] });

/* ================= 3. decimals & conversion ================= */
XP.add({ key:'en-ar-dec', lang:'en', sk:'arith', ord:30, title:'Decimals and conversions', min:'4 min',
  goals:['Understand the places after the decimal point','Convert between fractions, decimals and percents','Memorize the conversions the test loves','Avoid the missing-place trap'],
  scenes:[
  { t:'What is a decimal?',
    items:{ g0:{type:'grid',x:60,y:82,rows:10,cols:10,cell:20,gap:2,fill:0}, g30:{type:'grid',x:60,y:82,rows:10,cols:10,cell:20,gap:2,fill:30,c:'pri'},
      g25:{type:'grid',x:60,y:82,rows:10,cols:10,cell:20,gap:2,fill:25,c:'pink'},
      e1:{type:'eq',x:460,y:130,s:36,text:'3/10 = 0.3'}, e2:{type:'eq',x:460,y:195,s:36,text:'25/100 = 0.25',cls:'t-pri'},
      n1:{type:'note',x:375,y:278,w:130,h:58,c:'n3',text:'2 tenths',size:21,rot:-2}, n2:{type:'note',x:545,y:278,w:170,h:58,c:'n1',text:'5 hundredths',size:19,rot:2} },
    beats:[
      { say:'A decimal is a fraction over ten, a hundred or a thousand, written with a point.', show:['g0'] },
      { say:'Three rows out of ten is three tenths, written zero point three.', hide:['g0'], show:['g30','e1'] },
      { say:'Twenty-five squares out of a hundred is zero point two five.', hide:['g30'], show:['g25','e2'] },
      { say:'The first place is tenths, the second hundredths: two tenths and five hundredths.', show:['n1','n2'] },
    ]},
  { t:'Three names, one value',
    items:{ nF:{type:'note',x:320,y:100,w:120,h:66,c:'n2',text:'1/2',size:34}, lF:{type:'text',x:320,y:160,s:18,text:'fraction',cls:'t-ink2'},
      nD:{type:'note',x:140,y:255,w:120,h:66,c:'n3',text:'0.5',size:34}, lD:{type:'text',x:140,y:315,s:18,text:'decimal',cls:'t-ink2'},
      nP:{type:'note',x:500,y:255,w:120,h:66,c:'n1',text:'50%',size:34}, lP:{type:'text',x:500,y:315,s:18,text:'percent',cls:'t-ink2'},
      a1:{type:'arrow',x1:250,y1:112,x2:160,y2:210,bend:0,cls:'s-pri'}, t1:{type:'text',x:120,y:150,s:20,text:'top ÷ bottom',hand:true},
      a2:{type:'arrow',x1:215,y1:255,x2:425,y2:255,bend:-40,cls:'s-pri'}, t2:{type:'eq',x:320,y:222,s:22,text:'× 100',cls:'t-pri'},
      a3:{type:'arrow',x1:480,y1:210,x2:390,y2:112,bend:0,cls:'s-pink'}, t3:{type:'text',x:530,y:150,s:20,text:'÷ 100, simplify',hand:true} },
    beats:[
      { say:'Fraction, decimal and percent are three names for one value. Take one half.', show:['nF','lF'] },
      { say:'Fraction to decimal: divide top by bottom. One divided by two is zero point five.', show:['a1','t1','nD','lD'] },
      { say:'Decimal to percent: multiply by a hundred, moving the point two places. Fifty percent.', show:['a2','t2','nP','lP'] },
      { say:'Back to a fraction: divide by a hundred and simplify. Fifty over a hundred is a half.', show:['a3','t3'] },
    ]},
  { t:'Conversions to know',
    items:Object.assign({}, trow('h',80,'Fraction','Decimal','Percent',{hdr:true}), trow('r1',120,'1/2','0.5','50%'), trow('r2',160,'1/4','0.25','25%'),
      trow('r3',200,'3/4','0.75','75%'), trow('r4',240,'1/5','0.2','20%'), trow('r5',280,'1/8','0.125','12.5%'),
      { trap:{type:'note',x:320,y:326,w:300,h:44,c:'n1',text:'0.05 = 5%, not 50%',size:22,rot:-1} }),
    beats:[
      { say:'Some conversions come up again and again, so learn them. A half is fifty percent.', show:[...rk('h'),...rk('r1')], gap:.15 },
      { say:'A quarter is twenty-five percent; three quarters, seventy-five percent.', show:[...rk('r2'),...rk('r3')], gap:.12 },
      { say:'A fifth is twenty percent; an eighth, twelve and a half percent.', show:[...rk('r4'),...rk('r5')], gap:.12 },
      { say:'Watch the places: zero point zero five is only five percent, not fifty.', show:['trap'] },
    ]},
  { t:'Your turn: convert',
    items:{ q:{type:'eq',x:320,y:92,s:44,text:'3/8 = ?%'}, hint:{type:'text',x:320,y:135,s:22,text:'Remember: 1/8 = 12.5%',hand:true},
      res:{type:'box',x:150,y:190,w:340,h:62,c:'n0',text:'3 × 12.5 = 37.5%',s:30,cls:'t-note',ltr:true}, ck:{type:'check',x:320,y:295} },
    beats:[
      { say:'Your turn. Write three eighths as a percent.', show:['q'] },
      { say:'One eighth is twelve and a half percent. So what are three eighths?', show:['hint'] },
    ],
    ask:{ opts:['38%','37.5%','3.75%','0.375%'], a:1,
      right:'Well done! Three times twelve and a half is thirty-seven and a half percent.',
      wrong:'One eighth is twelve and a half percent, so three eighths is three times that: thirty-seven and a half.',
      show:['res','ck'] } },
  ],
  quiz:[
    {q:'0.6 is equal to:', o:['6/100','3/5','6%','2/3'], a:1, e:'0.6 = 6/10 = 3/5 after dividing top and bottom by 2.'},
    {q:'Which number is the largest?', o:['0.09','8%','1/10','0.099'], a:2, e:'1/10 = 0.1, which is bigger than 0.099, 0.09 and 0.08.'},
    {q:'45% as a fraction in simplest form:', o:['45/10','9/20','9/2','4/5'], a:1, e:'45/100, then divide top and bottom by 5 to get 9/20.'},
  ] });

/* ================= 4. percent (rebuilt from the hand-built Arabic lesson) ================= */
XP.add({ key:'en-percent', lang:'en', sk:'arith', ord:40, title:'Percentages from zero', min:'4 min',
  goals:['See what a percent means on a hundred-square','Turn a percent into a familiar fraction','Find 10%, 5% and 20% in your head','Avoid the “up then down” trap'],
  scenes:[
  { t:'Out of every hundred',
    items:{ g0:{type:'grid',x:40,y:66,rows:10,cols:10,cell:22,gap:2,fill:0}, g25:{type:'grid',x:40,y:66,rows:10,cols:10,cell:22,gap:2,fill:25,c:'pri'},
      title:{type:'text',x:470,y:120,s:30,text:'Percent'}, sub:{type:'text',x:470,y:160,s:22,text:'= how many out of 100?',hand:true},
      cnt:{type:'eq',x:470,y:212,s:26,text:'25 out of 100',cls:'t-ink2'},
      big:{type:'note',x:470,y:285,w:160,h:76,c:'n0',text:'25%',size:44,rot:-4} },
    beats:[
      { say:'A percent answers just one question: how many out of every hundred?', show:['g0','title','sub'], gap:.3 },
      { say:'Here are one hundred squares. Let’s shade twenty-five of them.', hide:['g0'], show:['g25','cnt'] },
      { say:'Twenty-five out of a hundred is written twenty-five percent.', show:['big'] },
    ]},
  { t:'A fraction in disguise',
    items:{ eq:{type:'eq',x:320,y:92,s:34,text:'25% = 25 ÷ 100 = 1/4'},
      pie:{type:'pie',cx:320,cy:220,r:85,parts:4,fill:1,c:'pink'},
      n1:{type:'note',x:130,y:220,w:170,h:84,c:'n1',text:'50% = 1/2',size:26,rot:-4},
      n2:{type:'note',x:320,y:220,w:170,h:84,c:'n0',text:'25% = 1/4',size:26,rot:3},
      n3:{type:'note',x:510,y:220,w:170,h:84,c:'n3',text:'10% = 1/10',size:26,rot:-2} },
    beats:[
      { say:'Every percent is a fraction with a denominator of one hundred.', show:['eq'] },
      { say:'And twenty-five out of a hundred is exactly one quarter.', show:['pie'] },
      { say:'Learn these three: fifty percent is a half, twenty-five a quarter, and ten a tenth.', hide:['pie'], show:['n1','n2','n3'], gap:.5 },
    ]},
  { t:'The ten-percent trick',
    items:{ q:{type:'eq',x:320,y:84,s:30,text:'10% of 240 = ?'},
      d2:{type:'text',x:135,y:185,s:72,text:'2'}, d4:{type:'text',x:190,y:185,s:72,text:'4'}, d0:{type:'text',x:245,y:185,s:72,text:'0'},
      ar:{type:'arrow',x1:290,y1:160,x2:400,y2:160,cls:'s-pri',bend:-30,text:'÷ 10'},
      res:{type:'note',x:475,y:160,w:130,h:80,c:'n0',text:'24',size:46,rot:-3},
      ch1:{type:'note',x:190,y:290,w:250,h:60,c:'n2',text:'20% = 2 × 24 = 48',size:22,rot:-2},
      ch2:{type:'note',x:450,y:290,w:250,h:60,c:'n1',text:'5% = 24 ÷ 2 = 12',size:22,rot:2} },
    beats:[
      { say:'To find ten percent of any number, divide it by ten.', show:['q','d2','d4','d0'], gap:.15 },
      { say:'In other words, drop one zero: two hundred and forty becomes twenty-four.', move:{d0:[0,50]}, hide:['d0'], show:['ar','res'] },
      { say:'Build from there: twenty percent is double, forty-eight. Five percent is half, twelve.', show:['ch1','ch2'], gap:1.2 },
    ]},
  { t:'Your turn: shade 40%',
    items:{ g0:{type:'grid',x:200,y:62,rows:10,cols:10,cell:22,gap:2,fill:0},
      q:{type:'text',x:320,y:92,s:24,text:'Each column holds 10 squares.'},
      g40:{type:'grid',x:50,y:124,rows:10,cols:10,cell:20,gap:2,fill:40,c:'pink'},
      p:{type:'note',x:470,y:190,w:160,h:76,c:'n0',text:'40%',size:44,rot:-3},
      e:{type:'eq',x:470,y:270,s:24,text:'40 out of 100',cls:'t-ink2'}, ck:{type:'check',x:470,y:315} },
    beats:[
      { say:'Your turn. This grid has ten columns of ten squares.', show:['g0'] },
      { say:'How many whole columns do you shade to show forty percent?', hide:['g0'], show:['q'] },
    ],
    ask:{ opts:['4 columns','6 columns','40 columns'], a:0,
      right:'Excellent! Four columns of ten make forty squares out of a hundred.',
      wrong:'Close! Forty percent is forty squares out of a hundred: four full columns of ten.',
      show:['g40','p','e','ck'] } },
  { t:'Discounts and a classic trap',
    items:{ bar:{type:'box',x:100,y:80,w:400,h:46,c:'n3',text:'200 riyals',s:24,cls:'t-note'},
      seg:{type:'box',x:400,y:80,w:100,h:46,c:'pink',text:'−50',s:22,cls:'t-note',ltr:true},
      tag:{type:'note',x:568,y:70,w:110,h:48,c:'n1',text:'25% off',size:20,rot:10},
      after:{type:'eq',x:300,y:162,s:24,text:'After the discount: 150 riyals',cls:'t-pri'},
      v1:{type:'note',x:140,y:275,w:110,h:64,c:'n0',text:'100',size:32}, v2:{type:'note',x:320,y:275,w:110,h:64,c:'n0',text:'120',size:32}, v3:{type:'note',x:500,y:275,w:110,h:64,c:'n1',text:'96',size:32},
      a1:{type:'arrow',x1:200,y1:246,x2:262,y2:246,cls:'s-pri',bend:-26}, l1:{type:'eq',x:231,y:212,s:18,text:'+20%',cls:'t-pri'},
      a2:{type:'arrow',x1:380,y1:246,x2:442,y2:246,cls:'s-pink',bend:-26}, l2:{type:'text',x:411,y:212,s:18,text:'−20% of 120',hand:true} },
    beats:[
      { say:'A shirt costs two hundred riyals, with twenty-five percent off.', show:['bar','tag'] },
      { say:'A quarter of two hundred is fifty, so you pay one hundred and fifty.', show:['seg','after'] },
      { say:'A famous trap: up twenty percent, then down twenty percent, does not bring you back.', show:['v1','a1','l1','v2','a2','l2','v3'], gap:.35 },
      { say:'The drop is taken from one hundred and twenty, not one hundred, so you end at ninety-six.', hl:['v3'] },
    ]},
  ],
  quiz:[
    {q:'What is 15% of 400?', o:['40','60','75','15'], a:1, e:'10% of 400 = 40, and 5% is half of that = 20. Total: 60.'},
    {q:'A price of 80 riyals after a 25% discount is:', o:['55 riyals','60 riyals','20 riyals','65 riyals'], a:1, e:'A quarter of 80 = 20, and 80 − 20 = 60.'},
    {q:'A number rises 10%, then falls 10%. Compared with the start, it is:', o:['the same','1% more','1% less','10% less'], a:2, e:'100 → 110 → 99, so 1% less, because the drop is taken from 110.'},
  ] });

/* ================= 5. ratio & proportion ================= */
const S1c=['pink','pink','sky','sky','sky'];
XP.add({ key:'en-ar-ratio', lang:'en', sk:'arith', ord:50, title:'Ratio and proportion', min:'4 min',
  goals:['See a ratio as a comparison of two amounts','Share an amount in a given ratio using parts','Solve a proportion by cross-multiplying','Answer part-of-a-whole questions quickly'],
  scenes:[
  { t:'What is a ratio?',
    items:Object.assign({ d1:{type:'circle',cx:140,cy:110,r:20,c:'pink'}, d2:{type:'circle',cx:190,cy:110,r:20,c:'pink'},
      d3:{type:'circle',cx:400,cy:110,r:20,c:'sky'}, d4:{type:'circle',cx:450,cy:110,r:20,c:'sky'}, d5:{type:'circle',cx:500,cy:110,r:20,c:'sky'},
      l1:{type:'text',x:165,y:160,s:18,text:'pink',cls:'t-ink2'}, l2:{type:'text',x:450,y:160,s:18,text:'blue',cls:'t-ink2'},
      r:{type:'eq',x:295,y:125,s:46,text:'2 : 3',cls:'t-pri'} },
      strip('p',{x:120,y:200,w:400,h:48,n:5,colors:S1c}),
      { f1:{type:'eq',x:200,y:285,s:26,text:'2/5'}, f2:{type:'eq',x:400,y:285,s:26,text:'3/5'},
        dbl:{type:'eq',x:320,y:332,s:22,text:'4 : 6 is the same as 2 : 3',cls:'t-hand'} }),
    beats:[
      { say:'A ratio compares two amounts. This bag holds two pink balls and three blue.', show:['d1','d2','d3','d4','d5','l1','l2'], gap:.12 },
      { say:'We say the ratio of pink to blue is two to three.', show:['r'] },
      { say:'The whole is five parts: pink is two fifths, blue is three fifths.', show:[...ks('p',5),'f1','f2'], gap:.12 },
      { say:'Doubling both amounts keeps the ratio: four to six is still two to three.', show:['dbl'] },
    ]},
  { t:'Sharing in a ratio',
    items:Object.assign({ q:{type:'eq',x:320,y:92,s:24,text:'Share 45 riyals: Khalid : Saad = 2 : 3'} },
      strip('p',{x:120,y:125,w:400,h:56,n:5,colors:S1c,texts:['','','','',''],s:26,cls:'t-note'}),
      { e:{type:'eq',x:320,y:238,s:36,text:'45 ÷ 5 = 9'},
        k:{type:'note',x:200,y:300,w:160,h:54,c:'n1',text:'Khalid: 18',size:24,rot:-2}, s:{type:'note',x:440,y:300,w:160,h:54,c:'n3',text:'Saad: 27',size:24,rot:2} }),
    beats:[
      { say:'Share forty-five riyals between Khalid and Saad in the ratio two to three.', show:['q'] },
      { say:'Add the parts: two plus three makes five equal parts.', show:ks('p',5), gap:.12 },
      { say:'One part is forty-five divided by five: nine.', show:['e'], set:{p0:'9',p1:'9',p2:'9',p3:'9',p4:'9'} },
      { say:'Khalid gets two parts, eighteen riyals. Saad gets three, twenty-seven riyals.', show:['k','s'] },
    ]},
  { t:'Proportions and cross-multiplying',
    items:{ q:{type:'eq',x:320,y:88,s:22,text:'3 pens cost 12 riyals. How much do 7 pens cost?'},
      n1:{type:'text',x:230,y:150,s:40,text:'3'}, b1:{type:'line',x1:200,y1:163,x2:260,y2:163}, d1:{type:'text',x:230,y:205,s:40,text:'12'},
      n2:{type:'text',x:410,y:150,s:40,text:'7'}, b2:{type:'line',x1:380,y1:163,x2:440,y2:163}, d2:{type:'text',x:410,y:205,s:40,text:'x',cls:'t-pri'},
      x1:{type:'line',x1:255,y1:130,x2:385,y2:200,cls:'s-pink'}, x2:{type:'line',x1:255,y1:200,x2:385,y2:130,cls:'s-pink'},
      eqs:{type:'box',x:303,y:150,w:34,h:26,rx:6,c:'surface',stroke:false,text:'=',s:40},
      e:{type:'eq',x:320,y:258,s:28,text:'3 × x = 12 × 7 = 84'},
      ans:{type:'box',x:230,y:282,w:180,h:52,c:'n0',text:'x = 28',s:28,cls:'t-note',ltr:true} },
    beats:[
      { say:'A proportion is two equal ratios. Three pens cost twelve riyals. What do seven cost?', show:['q'] },
      { say:'Write two equal fractions: three over twelve equals seven over x.', show:['n1','b1','d1','eqs','n2','b2','d2'], gap:.1 },
      { say:'Cross-multiply: three times x equals twelve times seven, eighty-four.', show:['x1','x2','e'] },
      { say:'Divide by three: x equals twenty-eight riyals.', show:['ans'] },
    ]},
  { t:'Your turn: parts of a whole',
    items:Object.assign({ q1:{type:'text',x:320,y:84,s:22,text:'A box holds 35 pens.'}, q2:{type:'eq',x:320,y:122,s:22,text:'Blue : red = 3 : 4. How many pens are red?'} },
      strip('p',{x:110,y:180,w:420,h:52,n:7,colors:['sky','sky','sky','bad','bad','bad','bad'],texts:['5','5','5','5','5','5','5'],s:24,cls:'t-note'}),
      { e:{type:'box',x:210,y:262,w:220,h:54,c:'n0',text:'4 × 5 = 20',s:28,cls:'t-note',ltr:true} }),
    beats:[
      { say:'Your turn. A box holds thirty-five pens, and the ratio of blue to red is three to four.', show:['q1','q2'] },
      { say:'Add the parts, find one part, then answer: how many are red?', hl:['q2'] },
    ],
    ask:{ opts:['15','20','28','25'], a:1,
      right:'Excellent! Seven parts, each worth five pens, and red is four parts: twenty pens.',
      wrong:'Three plus four is seven parts; one part is thirty-five divided by seven, five. Red is four times five: twenty.',
      show:[...ks('p',7),'e'] } },
  ],
  quiz:[
    {q:'60 riyals are shared in the ratio 1 : 4. How much is the larger share?', o:['15','48','40','12'], a:1, e:'5 parts, one part = 60 ÷ 5 = 12, so the larger share = 4 × 12 = 48.'},
    {q:'If x/5 = 12/20, what is x?', o:['3','4','6','2'], a:0, e:'Cross-multiply: 20 × x = 60, so x = 3.'},
    {q:'A car travels 120 km on 8 liters. How many liters does it need for 210 km?', o:['12','16','14','15'], a:2, e:'120/8 = 210/x, so x = 210 × 8 ÷ 120 = 14.'},
  ] });
})();
